// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plyrsflahsywxsbhwcxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseXJzZmxhaHN5d3hzYmh3Y3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMjU3OTAsImV4cCI6MjA1NTcwMTc5MH0.8W1FmJerKSHoldsWiEsq0OZTv5Vk8sAxzPLaNxafHrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);